server:
  port: 7001
    
management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: 
      path-mapping:
        health: /Status
  endpoint:
    health:
      enabled: true   
spring:
  application:
    name: VendorService
    
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties: 
      hibernate: 
        temp:
          use_jdbc_metadata_defaults: false 
        jdbc:
          lob:
            non_contextual_creation: true
        
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
    username: postgres
    password: anuhya
 